FROM ollama/ollama:latest

COPY Modelfile /

RUN ollama serve & \
    sleep 2 && \
    # ollama pull tinyllama && \
     ollama pull deepseek-r1 && \
    ollama create capsule-ai -f /Modelfile && \
    ollama rm deepseek-r1

    # When a container starts from this image, it will immediately start serving
# the 'capsule-ai' model on port 11434. This is the only instruction
# needed to start the server.
CMD [ "serve" ]
