FROM ollama/ollama:latest

ENV MODEL_NAME=kvison
ENV OLLAMA_MODEL=llama3.2-vision:11b


COPY Modelfile /

RUN ollama serve & \
    sleep 2 && \
    ollama pull ${OLLAMA_MODEL} && \
    #  ollama pull llama3:8b && \
    ollama create ${MODEL_NAME} -f /Modelfile && \
    ollama rm  ${OLLAMA_MODEL}

    # When a container starts from this image, it will immediately start serving
# the 'capsule-ai' model on port 11434. This is the only instruction
# needed to start the server.
CMD [ "serve" ]
