FROM ollama/ollama:latest

# Model and config
ENV MODEL_NAME=kvison
ENV OLLAMA_MODEL=llava:7b


COPY Modelfile /Modelfile

RUN set -eux; \
    ollama serve & \
    sleep 5 && \
    ollama pull ${OLLAMA_MODEL} && \
    ollama create ${MODEL_NAME} -f /Modelfile && \
    ollama rm ${OLLAMA_MODEL} && \
    rm -rf /root/.ollama/download/*


CMD ["serve"]



